### ISSUE TITLE
Missing authorizers: sls deploy error - self:custom.authorizers.status

### ISSUE THREAD

**Issue by MatthieuLab** [saumilsdk/saas-identity-cognito-lambda#1]
Hello @saumilsdk 

First thanks for your effort to port part of the Saas AWS approach in serverless.
I have clone your repo but I can not deploy.

_Serverless Warning --------------------------------------
 
  A valid service attribute to satisfy the declaration 'self:custom.authorizers.status' could not be found._

There is no custom.authorizers property in the serverless.yml. I would love some guidance.
Thanks
Matthieu

**Comment by saumilsdk** [comment]
Hi @MatthieuLab i have trimmed few things from the repository as it was private to my organization. You might want to fill it up by yourself and merge your changes to this repo. What you can do to fix your error is, remove all authorizer part from each lambda function.
